dist: trusty
language: python
python:
  - "3.5.3"
  - "3.6.1"
install:
  - pip install -r requirements.txt
script:
  - python -m compileall ./cogs
  - python -m pytest
cache: pip
notifications:
  email: false