server:
  port: 2333 # REST server
lavalink:
  server:
    password: "youshallnotpass"
    ws:
      host: "localhost"
      port: 2332
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    sentryDsn: ""
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 10000