name: Auto Labeler - PRs
on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Type Label
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: ""  # this is a temporary workaround, see #4844

      - name: Label documentation-only changes.
        uses: Jackenmen/label-doconly-changes@v1
        env:
          LDC_LABELS: Docs-only
